apiVersion: v1
kind: Pod
metadata:
  name: pod-annotation
  annotations:
    builder: "KDH(vataltrick@gmail.com)"
    buildDate: "2022-11-21"
    imageRegistry: https://hub.docker.com
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14
    ports:
    - containerPort: 80
      protocol: TCP
