apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  volumes:
  - name: html
    hostPath:
      type: Directory
      path: /webdata
  containers:
  - name: nginx
    image: nginx:1.14
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
