apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-bar
  namespace: fanoutns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      name: deploy-pod-bar
      labels:
        app: bar
    spec:
      containers:
      - name: bar-container
        image: whatwant/node-web:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bar-service
  namespace: fanoutns
spec:
  selector:
    app: bar
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
