---
apiVersion: v1
kind: Namespace
metadata:
  name: prodns
---
apiVersion: v1
kind: Pod
metadata:
  name: myweb
  namespace: prodns
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14
    ports:
    - containerPort: 80
      protocol: TCP
    env:
    - name: "DB"
      value: "mydb"
    resources:
      requests:
        cpu: "200m"
        memory: "500Mi"
      limits:
        cpu: "1"
        memory: "1000Mi"
