apiVersion: v1
kind: Pod
metadata:
  name: empty-pod
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: web-server
    image: nginx:1.14
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
