version: "3"

services:

  proxy:
    image: haproxytech/haproxy-alpine:2.4
    ports:
      - "80:80"
      - "8404:8404"
    networks:
      - mynet
    volumes:
      - "./config:/usr/local/etc/haproxy:ro"
    depends_on:
      - web
  
  web:
    image: webimage:2.0
    networks:
      - mynet
    links:
      - db:mysqldb
    depends_on:
      - db 
  
  db:
    image: mysql
    networks:
      - mynet
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - "mysql:/var/lib/mysql"

volumes:
  mysql:

networks:
  mynet:
