version: '3.3'

services:
  webserver:
    build: .
    ports:
      - "9001:80"
    links:
      - mysql:mysql
    restart: always
    volumes:
      - ./html:/var/www/html/
      - ./conf/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mysql

  mysql:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: soldesk
      MYSQL_PASSWORD: soldesk1.
      MYSQL_DATABASE: mydb
    volumes:
      - ./data:/var/lib/mysql
      - ./conf/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3306:3306"


