# base image configuration
FROM ubuntu:18.04

# nginx installation
RUN apt-get -y update && apt-get -y upgrade 
RUN apt-get -y install nginx

# port designation
EXPOSE 80

# deploy web content - not running now, but when next building start
ONBUILD ADD website.tar /var/www/html

# run nginx
CMD ["nginx", "-g", "daemon off;"]