apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: rs-pod-nginx
      labels:
        app: web
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14
