apiVersion: v1
kind: Pod
metadata:
  name: liveness-exam
spec:
  containers:
  - name: busybox-container
    image: busybox
    args:
    - "/bin/sh"
    - "-c"
    - "touch /tmp/healthy ; sleep 30 ; rm -f /tmp/healthy ; sleep 600"
    livenessProbe:
      exec:
        command:
        - "cat"
        - "/tmp/healthy"
      periodSeconds: 5
      initialDelaySeconds: 10
      successThreshold: 1
      failureThreshold: 2
